import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, CreditCard, LockKeyhole, MapPin, Minus, Plus, ShieldCheck, TicketPercent, Users, X } from 'lucide-react'
import type { Space } from './App'

type Step = 'details' | 'review' | 'complete'
export default function Checkout({ space, initialGuests, selectedDate, onClose }: { space: Space; initialGuests: number; selectedDate: string; onClose: () => void }) {
  const [step, setStep] = useState<Step>('details')
  const [guests, setGuests] = useState(initialGuests)
  const [payment, setPayment] = useState('card')
  const [code, setCode] = useState(false)
  const nights = space.kind === 'Stay' || space.kind === 'Boutique stay' ? 2 : 1
  const subtotal = space.price * nights
  const service = Math.round(subtotal * 0.075)
  const total = useMemo(() => subtotal + service, [subtotal, service])
  const isComplete = step === 'complete'
  return <div className="checkout-backdrop" onMouseDown={onClose}><aside className="checkout" onMouseDown={(event) => event.stopPropagation()}>{!isComplete && <button className="checkout-close" onClick={onClose}><X size={19}/></button>}<div className="checkout-progress"><span className={step === 'details' ? 'active' : 'done'}>{step === 'details' ? '1' : <Check size={12}/>} Details</span><i/><span className={step === 'review' ? 'active' : step === 'complete' ? 'done' : ''}>{step !== 'details' ? <Check size={12}/> : '2'} Review</span><i/><span className={isComplete ? 'active done' : ''}>{isComplete ? <Check size={12}/> : '3'} Confirmed</span></div>{isComplete ? <Success space={space} onClose={onClose} /> : <><header className="checkout-head"><p className="kicker">{step === 'details' ? 'SECURE RESERVATION' : 'ALMOST THERE'}</p><h2>{step === 'details' ? 'Plan your visit.' : 'Review and confirm.'}</h2></header><div className="checkout-layout"><section className="checkout-form">{step === 'details' ? <Details guests={guests} setGuests={setGuests} selectedDate={selectedDate} space={space}/> : <Review payment={payment} setPayment={setPayment} code={code} setCode={setCode}/>}</section><aside className="order-summary"><img src={space.image} alt={space.name}/><div className="summary-space"><small>{space.kind}</small><h3>{space.name}</h3><p><MapPin size={13}/>{space.place}</p></div><div className="summary-line"><span>{nights > 1 ? `${nights} nights` : 'Reservation'} <i>× {guests} guest{guests > 1 ? 's' : ''}</i></span><strong>₦{subtotal.toLocaleString()}</strong></div><div className="summary-line"><span>Service fee</span><strong>₦{service.toLocaleString()}</strong></div><div className="summary-total"><span>Total</span><strong>₦{total.toLocaleString()}</strong></div><p className="summary-note"><ShieldCheck size={14}/> Your reservation is protected by ReserveFlow.</p></aside></div><footer className="checkout-footer">{step === 'review' ? <button className="back-button" onClick={() => setStep('details')}><ArrowLeft size={16}/> Back</button> : <span><LockKeyhole size={14}/> Encrypted and secure</span>}<button className="continue-button" onClick={() => setStep(step === 'details' ? 'review' : 'complete')}>{step === 'details' ? <>Continue to review <ArrowRight size={16}/></> : <><LockKeyhole size={15}/> Confirm reservation</>}</button></footer></>}</aside></div>
}

function Details({ space, guests, setGuests, selectedDate }: { space: Space; guests: number; setGuests: (value: number) => void; selectedDate: string }) { return <><h3>When are you visiting?</h3><div className="visit-grid"><div><CalendarDays size={18}/><span><small>DATE</small><b>{selectedDate}, 14 Oct</b></span><ChevronDown size={15}/></div><div><CalendarDays size={18}/><span><small>{space.kind === 'Stay' || space.kind === 'Boutique stay' ? 'CHECK OUT' : 'TIME'}</small><b>{space.kind === 'Stay' || space.kind === 'Boutique stay' ? 'Thu, 16 Oct' : '10:30 AM'}</b></span><ChevronDown size={15}/></div></div><h3>Who is this for?</h3><div className="guest-picker"><Users size={18}/><div><b>{guests} guest{guests > 1 ? 's' : ''}</b><small>{space.seats}</small></div><div><button onClick={() => setGuests(Math.max(1, guests - 1))}><Minus size={13}/></button><button onClick={() => setGuests(guests + 1)}><Plus size={13}/></button></div></div><div className="policy-card"><ShieldCheck size={18}/><div><b>Flexible by default</b><p>Cancel within 24 hours of booking for a full refund. Your final policy will be shown before payment.</p></div></div></> }
function Review({ payment, setPayment, code, setCode }: { payment: string; setPayment: (value: string) => void; code: boolean; setCode: (value: boolean) => void }) { return <><h3>How would you like to pay?</h3><div className="payment-options"><button className={payment === 'card' ? 'selected' : ''} onClick={() => setPayment('card')}><CreditCard size={19}/><span><b>Credit or debit card</b><small>Visa, Mastercard, Verve</small></span><i/></button><button className={payment === 'transfer' ? 'selected' : ''} onClick={() => setPayment('transfer')}><span className="bank-mark">₦</span><span><b>Bank transfer</b><small>Instant confirmation</small></span><i/></button></div><button className="promo-button" onClick={() => setCode(!code)}><TicketPercent size={17}/> Have a promo code? <ChevronDown size={15}/></button>{code && <div className="promo-input"><input placeholder="Enter code"/><button>Apply</button></div>}<div className="review-notice"><LockKeyhole size={17}/><p>Payment is securely processed. We never store your full card details.</p></div></> }
function Success({ space, onClose }: { space: Space; onClose: () => void }) { return <div className="success-state"><span><Check size={28}/></span><p className="kicker">RESERVATION CONFIRMED</p><h2>You’re all set.</h2><p>Your reservation at <b>{space.name}</b> is confirmed. We’ve sent every detail to your email.</p><div className="reference"><small>RESERVATION REFERENCE</small><strong>RF-8K2P-104</strong></div><button onClick={onClose}>View my reservations <ArrowRight size={16}/></button></div> }
