import { useState } from 'react'
import { ArrowRight, CalendarDays, Check, ChevronRight, Clock3, MapPin, MoreHorizontal, ShieldCheck, UserRound } from 'lucide-react'
import './ReservationsHub.css'

type Status = 'Confirmed' | 'Pending' | 'Checked in' | 'Completed' | 'Cancelled'
type Reservation = { id: string; guest: string; initials: string; space: string; date: string; amount: string; status: Status; image: string }
const reservations: Reservation[] = [
  { id: 'RF-8K2P-104', guest: 'Amara Mensah', initials: 'AM', space: 'The Glasshouse', date: '15–17 Oct · 2 nights', amount: '₦180,300', status: 'Confirmed', image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=280&q=75' },
  { id: 'RF-2M7A-511', guest: 'Tunde Adeleke', initials: 'TA', space: 'Sonder Social', date: '16 Oct · 09:00', amount: '₦12,500', status: 'Pending', image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=280&q=75' },
  { id: 'RF-4W9L-338', guest: 'Nora Williams', initials: 'NW', space: 'Axis Health', date: '18 Oct · 10:30', amount: '₦18,000', status: 'Checked in', image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=280&q=75' },
]
const states: Status[] = ['Pending', 'Confirmed', 'Checked in', 'Completed']

export default function ReservationsHub() {
  const [selected, setSelected] = useState(reservations[0])
  const [filter, setFilter] = useState<Status | 'All'>('All')
  const [list, setList] = useState(reservations)
  const filtered = filter === 'All' ? list : list.filter((item) => item.status === filter)
  const advance = () => { const index = states.indexOf(selected.status); if (index < states.length - 1) { const updated = { ...selected, status: states[index + 1] }; setSelected(updated); setList((items) => items.map((item) => item.id === updated.id ? updated : item)) } }
  const activeIndex = states.indexOf(selected.status)
  return <section className="reservations-section"><div className="shell"><div className="reservations-heading"><div><p className="kicker">RESERVATION LIFECYCLE</p><h2>Every booking,<br/><em>under control.</em></h2></div><p>A front-end model of the workflows guests, vendors, and support teams need to handle each reservation with confidence.</p></div><div className="reservation-console"><div className="console-list"><div className="console-list-head"><div><strong>Reservations</strong><span>{list.length} active</span></div><button><CalendarDays size={15}/> Calendar</button></div><div className="status-filter">{(['All', 'Confirmed', 'Pending', 'Checked in'] as const).map((status) => <button key={status} className={filter === status ? 'active' : ''} onClick={() => setFilter(status)}>{status}</button>)}</div><div className="reservations-list">{filtered.map((reservation) => <button className={selected.id === reservation.id ? 'reservation-item active' : 'reservation-item'} onClick={() => setSelected(reservation)} key={reservation.id}><img src={reservation.image} alt=""/><span><b>{reservation.space}</b><small>{reservation.guest} · {reservation.date}</small><em className={`status ${reservation.status.toLowerCase().replace(' ', '-')}`}>{reservation.status}</em></span><ChevronRight size={16}/></button>)}{filtered.length === 0 && <p className="no-reservations">No matching reservations.</p>}</div></div><div className="reservation-detail"><header><div><small>RESERVATION {selected.id}</small><h3>{selected.space}</h3></div><button><MoreHorizontal size={19}/></button></header><div className="detail-guest"><img src={selected.image} alt=""/><div><span className="guest-initials">{selected.initials}</span><div><b>{selected.guest}</b><small>Primary guest · verified</small></div></div><strong>{selected.amount}</strong></div><div className="state-track">{states.map((state, index) => <div className={index <= activeIndex ? 'reached' : ''} key={state}><span>{index < activeIndex ? <Check size={12}/> : index + 1}</span><b>{state}</b>{index < states.length - 1 && <i/>}</div>)}</div><div className="detail-meta"><span><CalendarDays size={16}/><div><small>WHEN</small><b>{selected.date}</b></div></span><span><MapPin size={16}/><div><small>WHERE</small><b>Victoria Island, Lagos</b></div></span><span><UserRound size={16}/><div><small>GUESTS</small><b>2 guests</b></div></span></div><div className="detail-actions"><div><ShieldCheck size={17}/><p><b>Payment protected</b><small>Payment is captured and ready for payout after completion.</small></p></div>{activeIndex < states.length - 1 ? <button onClick={advance}>{selected.status === 'Pending' ? 'Confirm reservation' : selected.status === 'Confirmed' ? 'Check in guest' : 'Complete stay'} <ArrowRight size={16}/></button> : <button className="complete" disabled><Check size={16}/> Completed</button>}</div></div></div></div></section>
}
